const EventActions = {
  JOIN_EVENT_START: "JOIN_EVENT_START",
  JOIN_EVENT_SUCCESS: "JOIN_EVENT_SUCCESS",
  JOIN_EVENT_DENY: "JOIN_EVENT_DENY",
  JOIN_EVENT_FAILURE: "JOIN_EVENT_FAILURE",

  EXIST_EVENT_START: "EXIST_EVENT_START",
  EXIST_EVENT_SUCCESS: "EXIST_EVENT_SUCCESS",
  EXIST_EVENT_NOT_EXIST: "EXIST_EVENT_NOT_EXIST",
  EXIST_EVENT_FAILURE: "EXIST_EVENT_FAILURE",

  UPDATE_EVENT: "UPDATE_EVENT",
}

export default EventActions
